apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      nodePort: 32020
      port: {{ .Values.servicePort }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.app }}
